### ISSUE TITLE
Extract utils into a separate package

### ISSUE THREAD

**Issue by connor-baer** [sumup-oss/circuit-ui#468]
## Purpose

Circuit UI exports a number of utility functions for dealing with [currencies](https://github.com/sumup/circuit-ui/blob/canary/src/util/currency.js) and [numbers](https://github.com/sumup/circuit-ui/blob/canary/src/util/numbers.js). IMO, these should be distributed separately, for the following reasons:

1. Using the utility functions without Circuit UI or even React, e.g. in a Node backend.
2. Upgrading the utility functions without having to upgrade components.

Circuit UI is a _component_ library. It should contain/expose as little logic as possible.

## Tasks

- [x] Pick a name for the package → "Intl"
- [x] Create a new repository under the [SumUp OSS](https://github.com/sumup-oss/) GitHub org
- [x] Initialize the repo with [Foundry](github.com/sumup/foundry)
- [ ] Move the [currencies](https://github.com/sumup/circuit-ui/blob/canary/src/util/currency.js) and [numbers](https://github.com/sumup/circuit-ui/blob/canary/src/util/numbers.js) and code to the new project
- [x] Replicate build script from Foundry to transpile the code to different formats
- [ ] Publish the package to NPM (@connor-baer can help with access rights)
- [ ] Delete the code from Circuit UI and add the package as a peer dependency

**Optional**

- [ ] Migrate the code to TypeScript
- [ ] Review and improve the APIs
- [ ] Investigate how the [`Intl`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) browser API could replace some of the code

**Comment by fernandofleury** [comment]
I think we could move this to our "i18n" library. It's not uncommon to have something like this. What do you think?

**Comment by connor-baer** [comment]
Could make sense. What else does a i18n library usually contain?

**Comment by connor-baer** [comment]
I like the idea of grouping it this way 👍

**Comment by connor-baer** [comment]
- Give flexibility to the consuming application to choose the library of their choice
- Maybe there's a third-party library we can use?

**Comment by connor-baer** [comment]
Work in progress here: https://github.com/sumup-oss/intl-js/
