### ISSUE TITLE
Component roadmap

### ISSUE THREAD

**Issue by connor-baer** [sumup-oss/circuit-ui#469]
_Based on an [internal document](https://docs.google.com/document/d/1eGgEvX9kjk5N0nITT7B03T9qGd-dBlkiZIVLYrMGDvI/edit) which should be treated as the source of truth._

## Deprecated

_These components will likely be removed in the next major version._

- [x] [CreditCardDetails](https://github.com/sumup/circuit-ui/tree/canary/src/components/CreditCardDetails): should be replaced by the new [card widget](https://developer.sumup.com/docs/widgets-card-v2)
- [x] [HtmlElement](https://github.com/sumup/circuit-ui/tree/canary/src/components/HtmlElement): should be replaced by Emotion 10’s `as` prop
- [x] [Markdown](https://circuit.sumup.com/components/markdown)
- [x] [MaskedInput](https://github.com/sumup/circuit-ui/tree/canary/src/components/MaskedInput): just a re-export of [`react-text-mask`](https://github.com/text-mask/text-mask)
- [x] [Picture](https://github.com/sumup/circuit-ui/tree/canary/src/components/Picture)
- [x] [SideNav](https://github.com/sumup/circuit-ui/tree/canary/src/components/SideNav): should be replaced by [Sidebar](https://circuit.sumup.com/components/sidebar)

## Under review

_These components are stable, but might have breaking changes in the next major version._

- [x] [Button](https://circuit.sumup.com/components/button): some of its responsibility should be moved to a link component (#466)
- [x] [GlobalStyles](https://github.com/sumup/circuit-ui/tree/canary/src/components/GlobalStyles): remove support for custom styles (to discourage wrong usage) + rename to BaseStyles
- [x] [ListView](https://github.com/sumup/circuit-ui/tree/canary/src/components/ListView): rename to CardList
- [x] [SvgButton](https://circuit.sumup.com/storybook/?path=/story/components-svgbutton--default-svgbutton): rename to IconButton
- [ ] [Calendar](https://circuit.sumup.com/components/calendar): rename to DatePicker + consolidate components under one parent API
- [x] [Card Schemes](https://circuit.sumup.com/components/card-schemes), [InfoIcon](https://github.com/sumup/circuit-ui/tree/canary/src/components/InfoIcon): should be moved to a separate icons package #528 
- [x] [Message](https://circuit.sumup.com/components/message), [NotificationBanner](https://github.com/sumup/circuit-ui/tree/canary/src/components/NotificationBanner), [NotificationList](https://github.com/sumup/circuit-ui/tree/canary/src/components/NotificationList): rename and group with other notification components #541 
- [ ] [Header](https://github.com/sumup/circuit-ui/tree/canary/src/components/Header): needs a more specific name

## Experimental

_These components are **not stable** and will likely have breaking changes in the next major version._

- [x] [Pagination](https://circuit.sumup.com/components/pagination): review the API and test with different use cases + check accessibility
- [x] [AutoCompleteTags](https://circuit.sumup.com/components/forms#autocomplete-tags)

**Comment by fernandofleury** [comment]
Is this the moment for us to also cleanup the default margin from some of our components? Such as the `Input`. Right now we are using the `noMargin` prop.

**Comment by connor-baer** [comment]
This could be the time. We should do some research on how other component libraries handle this and have a separate discussion about it. 

I have some ideas on how to apply spacing, e.g. using Emotion 10's `css` prop with "mixins":

```js
// @sumup/circuit-ui/src/styles/shared.js
import { css } from '@emotion/core';

const spacing = (theme, size = 'kilo', direction = 'bottom') => css`
  margin-${direction}: ${theme.spacings[size]};
`;

// app/src/components/ButtonWithMargin.js 
import { css } from '@emotion/core';
import styled from '@emotion/styled';
import { Button, sharedStyles } from '@sumup/circuit-ui';

const ButtonWithMargin = props => (
  <Button css={theme => sharedStyles.spacing(theme)}>Example</Button>
);

// or

const buttonStyles = ({ theme }) => css`
  sharedStyles.spacing(theme);
  color: red;
`;

const StyledButton = styled(Button)(buttonStyles);
```

**Comment by fernandofleury** [comment]
I was thinking about providing actually both.

We need to extend `Spacing` to support multiples of the gutter, or a custom value, media query based values.

**Comment by connor-baer** [comment]
Ah, interesting thought! 👍

I'm gonna schedule a roadmap meeting for Circuit UI soon, let's continue the discussion then.

**Comment by connor-baer** [comment]
I've opened RFCs for the grid (#535) and spacing (#534).

**Comment by connor-baer** [comment]
This issue has been superseded by the other issues mentioned above.
