### ISSUE TITLE
[RFC] Typescript

### ISSUE THREAD

**Issue by herberthenrique** [sumup-oss/circuit-ui#516]
## Suggested technology

_- What technology do you suggest we start using?_
Type System, [TypeScript](https://www.typescriptlang.org/)

_- What problem does it solve?_
Having type system inside Circuit UI we want to solve problems like: 
1. Strict typing
Everything stays the way we define it. Need a variable to always be a number? It’ll always be a number, then.

2. Structural typing
Indispensable when you care about fully defining the actual structure you use. JavaScript allows for a lot of strange things to be done, so relying on a specific structure is a much safer solution.

3. Type annotations
A handy way of saying explicitly what type should be used.

4. Type inference
Implicit typing performed by TypeScript itself so that your developers don’t need to provide types where the compiler can find them on its own.

According to [StackOverflow’s 2019 survey](https://insights.stackoverflow.com/survey/2019#most-loved-dreaded-and-wanted), TypeScript is currently one of the most loved programming languages, tied with Python:

## Alternatives

_What are the alternatives you've explored? Why choose one over the other?_
We can use [Flow](https://flow.org/) for typing, but the community is not going on this direction and the library isn't been using in favor 

## Potential downsides

The biggest downside is related to the learning curves of new developers.
Learning type system if you only worked before with dynamic languages is kind of confusing.

## Components to be migrated (WIP):

- [x] Badge @hleote (#624)
- [x] BaseStyles
- [x] Blockquote @robinmetral (#617)
- [x] Button
- [x] ButtonGroup @connor-baer 
- [ ] Calendar, CalendarTag, CalendarTagTwoStep (⚠️ _under review_ #537)
- [x] Card @AlineLee 
- [x] CardList (⚠️ _under review_ #794)
- [ ] Carousel
- [x] Checkbox @wilfernandesjr 
- [x] CloseButton
- [ ] Grid, Row, Col (⚠️ _under review_ #535)
- [x] ComponentsContext
- [x] CurrencyInput @connor-baer
- [x] Hamburger
- [x] Header @hleote &  @JonathanMH (#806)
- [x] Heading @robinmetral (#594)
- [x] Hr @connor-baer 
- [x] IconButton (#585)
- [x] Image @jmaslate 
- [x] InlineElements @connor-baer (#825)
- [x] InlineNotification @connor-baer 
- [x] Input @connor-baer 
- [x] Label @connor-baer 
- [x] List @connor-baer (#593)
- [x] LoadingButton (#584)
- [x] Message @connor-baer 
- [x] Modal @connor-baer (#610) 
- [x] NotificationBanner @connor-baer 
- [x] NotificationList @connor-baer 
- [x] Pagination @connor-baer 
- [x] Popover (⚠️ _under review_ #723)
- [x] ProgressBar @connor-baer
- [x] RadioButton @connor-baer 
- [x] RadioButtonGroup @connor-baer 
- [x] SearchInput @connor-baer
- [x] Select @connor-baer 
- [x] Selector @connor-baer 
- [ ] SideNav (⚠️ _under review_ #789)
- [x] Spacing @amelako
- [x] Spinner
- [x] SubHeading @robinmetral (#612)
- [x] Table @robinmetral  (#852)
- [ ] Tabs
- [x] Tag @connor-baer 
- [x] Text @connor-baer (#581)
- [x] TextArea @connor-baer 
- [x] Toggle @connor-baer 
- [ ] Tooltip (⚠️ _under review_ #723)

**Comment by fernandofleury** [comment]
Let's make it happen!

**Comment by connor-baer** [comment]
Let's share (and vote on?) this RFC at the next global web chapter sync. I believe that most of the team is very much in favor of moving to TypeScript.

@herberthenrique I see that you created a checklist of components. Do you plan to migrate each component individually? How do you plan to handle the initial configuration? Have you investigated if all of our tooling supports TypeScript (I'm especially thinking about Emotion, Storybook, and Eslint/Prettier here)?

**Comment by fernandofleury** [comment]
@connor-baer I was planning we could create some spikes for the bootstrap and do it while I'm there at the São Paulo office next week

**Comment by hleote** [comment]
@herberthenrique nice RFC 👍 💯 

I've used some time on setting up the initial configuration, unfortunately didn't had time to finish it...

As @connor-baer mentions above, the biggest challenge I've faced when doing this was integrating typescript's initial config it with all the tooling already being used by circuit-ui...

I probably will need some help from someone that knows the project better than I do... 🙂

**Comment by connor-baer** [comment]
@hleote That's exciting! Could you push your initial configuration to a branch please so we can use it as a starting point?

**Comment by connor-baer** [comment]
We've effectively migrated most components to TypeScript. The few remaining components will be deprecated or rewritten from scratch.
