### ISSUE TITLE
Extract icons into a separate package

### ISSUE THREAD

**Issue by connor-baer** [sumup-oss/circuit-ui#528]
## Motivation

The design team is working on a unified icon collection. Circuit UI currently only includes a handful of icons, most icons are used inside applications directly. A separate icon package would allow us to easily distribute and use the icons and allow for changes and maintenance independent of Circuit UI.

## Tasks

- [x] ~Pick a name for the package~ ~Currents 🎉~ I went with "[@sumup/icons](https://github.com/sumup-oss/icons)" so it would be easier to find and understand what the package does. I think "Currents" would work well for the Figma plugin since it enables the flow of changes through the system, much like an electrical current.
- [x] Create a new repository under the [SumUp OSS](https://github.com/sumup-oss/) GitHub org (@connor-baer can help with access rights)
- [x] Decide on distribution format(s)
    - Export as raw (optimized) SVGs
    - Export as React components
    - Statically hosted on GitHub pages
- [x] Manually export SVGs from Figma
- [x] Publish the package to NPM (@connor-baer can help with access rights here as well)
- [x] Delete the code from Circuit UI and add the package as a peer (?) dependency
- [x] Deprecate the icon components, e.g. CardSchemes, InfoIcon, PaymentMethodIcon

**Optional**

- [ ] Write a Figma plugin to automate the release/update process
